[deprels.labels]
acl = [ "relcl",]
advcl = [ "relcl",]
advmod = []
amod = []
appos = []
aux = [ "pass",]
case = []
cc = [ "preconj",]
ccomp = []
compound = [ "prt",]
conj = []
cop = []
csubj = [ "outer", "pass",]
dep = []
det = [ "predet",]
discourse = []
dislocated = []
expl = []
fixed = []
flat = []
goeswith = []
iobj = []
list = []
mark = []
nmod = [ "desc", "poss", "unmarked",]
nsubj = [ "outer", "pass",]
nummod = []
obj = []
obl = [ "agent", "unmarked",]
orphan = []
parataxis = []
punct = []
reparandum = []
root = []
vocative = []
xcomp = []
